version: 2.1
orbs:
  hello: circleci/hello-build@0.0.5

parameters:  # Define global pipeline parameters
  email_to: 
    type: string
    default: "default@example.com"

jobs:
  show-repo-and-python-version:  # Job name
    parameters:  # Pass the pipeline parameter to the job
      email_to: 
        type: string
        default: "default@batman.com"
    docker:         # Execution environment
      - image: circleci/python:3.9  # Use a Python Docker image
    steps:          # Define the steps in the job
      - checkout                     # NOTE: Step to clone the repository
      - run:
          name: Print Hello World
          command: echo "I am trying!!"
      - run:
          name: Show repo folder
          command: |
            pwd
            ls -a
      - run:
          name: Check Python Version # Step to check Python version
          command: python --version  # Command to execute
      - run:
          name: Print Environment Variable
          command: |
            echo "Env email to form project settings: $EMAIL_TO"
            echo "Email passed as job parameter: << parameters.email_to >>"


workflows:
  cicleci-howto:       # Workflow that runs the job
    jobs:
      - hello/hello-build
      - show-repo-and-python-version:
          name: Show repo and python version
          email_to: << pipeline.parameters.email_to >>  # Pass pipeline parameter to the job. If ommit => defailt = 
          requires:
            - hello/hello-build
      - show-repo-and-python-version:
          name: Show repo and python version 2
          email_to:
          requires:
            - hello/hello-build
      - show-repo-and-python-version:
          name: Show repo and python version 2
          email_to: "default@agoravai.com.br"
          requires:
            - hello/hello-build
