version: 2.1
orbs:
  hello: circleci/hello-build@0.0.5

jobs:
  show-repo-and-python-version:  # Job name
    docker:         # Execution environment
      - image: circleci/python:3.9  # Use a Python Docker image
    steps:          # Define the steps in the job
      - checkout                     # NOTE: Step to clone the repository
      - run:
          name: Print Hello World
          command: echo "I am trying!!"
      - run:
          name: Show repo folder
          command: |
            pwd
            ls -a
      - run:
          name: Check Python Version # Step to check Python version
          command: python --version  # Command to execute
      - run:
          name: Print Environment Variable
          command: |
            echo $EMAIL_TO
            echo $GITUSERNAME

workflows:
  cicleci-howto:       # Workflow that runs the job
    jobs:
      - hello/hello-build
      - show-repo-and-python-version:
          name: Show repo and python version
          requires:
            - hello/hello-build
